# Docker containers for the Django server and MySQL database

services:

  django:

    container_name: transit_server

    build:
      context: ./backend

    volumes:
      - transit_server_data:/data
      - ./backend:/usr/src/backend

    environment:
      DJANGO_SETTINGS_MODULE: backend.settings
      TRANSIT_DB_HOST: mysql
      TRANSIT_DB_PORT: 3306
      TRANSIT_DB_NAME: ${TRANSIT_DB_NAME}
      TRANSIT_DB_PASSWORD: ${TRANSIT_DB_PASSWORD}
      TRANSIT_DB_USER: ${TRANSIT_DB_USER}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      TRANSLINK_API_KEY: ${TRANSLINK_API_KEY}
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    ports:
      - 8000:8000

#  cron:
#
#    container_name: cron_scheduler
#    build:
#      context: ./backend
#
#    environment:
#      DJANGO_SETTINGS_MODULE: backend.settings
#      TRANSIT_DB_HOST: mysql
#      TRANSIT_DB_PORT: 3306
#      TRANSIT_DB_NAME: ${TRANSIT_DB_NAME}
#      TRANSIT_DB_PASSWORD: ${TRANSIT_DB_PASSWORD}
#      TRANSIT_DB_USER: ${TRANSIT_DB_USER}
#      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
#      TRANSLINK_API_KEY: ${TRANSLINK_API_KEY}
#
#    volumes:
#      - transit_server_data:/data
#      - ./backend:/usr/src/backend
#    command: >
#      sh -c "python manage.py migrate django_cron && python manage.py runcrons"
#    depends_on:
#      - django
#      - mysql

  redis:

    image: redis:alpine

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  celery: # Celery Worker Node

    build:
      context: ./backend

    environment:
      DEBUG: 1
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${TRANSIT_ALLOWED_HOSTS}
      DJANGO_SETTINGS_MODULE: backend.settings
      TRANSIT_DB_HOST: mysql
      TRANSIT_DB_PORT: 3306
      TRANSIT_DB_NAME: ${TRANSIT_DB_NAME}
      TRANSIT_DB_PASSWORD: ${TRANSIT_DB_PASSWORD}
      TRANSIT_DB_USER: ${TRANSIT_DB_USER}

    command: celery -A backend worker -l info
    volumes:
      - ./backend:/usr/src/backend
      - transit_server_data:/data

    depends_on:
      - django
      - mysql
      - redis

  celery-beat: # Celery Task Scheduler
    build:
      context: ./backend

    command: celery -A backend beat -l info

    volumes:
      - ./backend:/usr/src/backend
      - transit_server_data:/data

    environment:
      DEBUG: 1
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${TRANSIT_ALLOWED_HOSTS}
      DJANGO_SETTINGS_MODULE: backend.settings
      TRANSIT_DB_HOST: mysql
      TRANSIT_DB_PORT: 3306
      TRANSIT_DB_NAME: ${TRANSIT_DB_NAME}
      TRANSIT_DB_PASSWORD: ${TRANSIT_DB_PASSWORD}
      TRANSIT_DB_USER: ${TRANSIT_DB_USER}

    depends_on:
      - django
      - mysql
      - redis

  mysql:

    container_name: transit_server_mysql_db
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${TRANSIT_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${TRANSIT_DB_PASSWORD}
    volumes:
      - transit_db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u ${TRANSIT_DB_USER} --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 2s
      timeout: 5s
      retries: 20
    ports:
      - 3307:3306   # Port 3307 is used to prevent conflicts with MySQL running locally

volumes:

  transit_server_data:
  transit_db_data:
